name: wrf_visualizer
channels:
  - conda-forge  # Primary channel for geospatial packages
  - defaults

dependencies:
  # Core Python
  - python=3.9.*  # Tested with 3.9 (best compatibility with cartopy)
  
  # Essential libraries
  - numpy=1.23.*
  - pandas=1.5.*
  - xarray=2023.1.*
  - netcdf4=1.6.2
  
  # WRF-specific
  - wrf-python=1.3.4.1  # Critical for WRF data extraction
  - cartopy=0.21.0  # Must come from conda-forge
  
  # Visualization
  - matplotlib=3.6.*
  - cartopy=0.21.0  # Geospatial plotting
  - geopandas=0.12.*  # Shapefile handling
  - descartes=1.1.*  # Required for geopandas plotting
  
  # Streamlit and UI
  - streamlit=1.23.*
  - streamlit-folium=0.11.*  # Optional for interactive maps
  
  # Geospatial dependencies
  - proj=9.1.*  # Coordinate transformations
  - gdal=3.6.*  # Geospatial data processing
  - shapely=2.0.*  # Geometry operations
  - fiona=1.9.*  # Shapefile I/O
  
  # Utilities
  - pip=22.3.*
  - pip:
      - python-dateutil==2.8.2  # Better datetime handling
      - pyproj==3.4.*  # Coordinate transformations
      - cmocean==2.0.*  # Additional colormaps (optional)
      - contextily==1.3.*  # Basemap tiles (optional)