name: wrf-streamlit-app
channels:
  - conda-forge
dependencies:
  - python=3.10
  - streamlit
  - matplotlib
  - cartopy
  - wrf-python
  - netcdf4
  - numpy
  - pandas
  - geopandas
  - shapely
  - xarray
  - pyproj
  - scipy  # Optional, if doing stats
  - metpy
  - pip:
      - beautifulsoup4
      - gdown
    
